GET {{flaskserver}}/user

###

GET {{flaskserver}}/user/userpk1

###

POST {{flaskserver}}/user
{{jsoncontent}}

{
  "name": "username 3",
  "email": "user_3@email.tld"
}

###

PUT {{flaskserver}}/user
{{jsoncontent}}

{
  "name": "updated username 3",
  "email": "updated_user_3@email.tld",
  "pk": "userpk3"
}

###

DELETE {{flaskserver}}/user/userpk3
