@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@server = http://{{host}}
@contentType = Content-Type: application/json

GET {{server}}/post_like/number-of-likes/postpk1

###

POST {{server}}/post_like
{{contentType}}

{
  "postPK": "postpk1",
  "userPK": "userpk1"
}

###

DELETE {{server}}/post_like/postpk1/userpk3
