# testing apis from myapp/apis/routes.py
@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@server = http://{{host}}
@contentType = Content-Type: application/json

# home
GET {{server}}/

###

#post_example
POST {{server}}/post/example
{{contentType}}
authorization-sha256: "test-auth-token"

{
  "request_id": "123",
  "payload": "test payload"
}
